spring:
  profiles:
    active: dev
  # redis
  redis:
    host: 182.92.152.31
    port: 6379
    password: 123456
    timeout: 5000
    database: 0

# Mybatis-Plus 配置
mybatis-plus:
  type-aliases-package: com.rui.admin.*.model.entity
  type-enums-package: com.rui.admin.*.model.entity
  mapper-locations: classpath*:com/rui/admin/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
