spring:
  profiles:
    active: dev
  # redis
  redis:
    host: 182.92.152.31
    port: 6379
    password: 123456
    timeout: 5000
    database: 0
    lettuce:
      pool:
        # 最大连接数
        max-active: 20
        # 最小空闲
        min-idle: 5
        # 链接超时
        max-wait: 5000ms
        # 最大空闲
        max-idle: 20

# Mybatis-Plus 配置
mybatis-plus:
  type-aliases-package: com.rui.admin.*.model.entity
  type-enums-package: com.rui.admin.*.model.entity
  mapper-locations: classpath*:com/rui/admin/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
