setting:
  # 作者
  author: Rui
  # 去除的表前缀,多个以 , 分隔, 不能有空格
  tablePrefix: sys_
  # 表名多个以 , 分隔, 不能有空格
  tableName: sys_role_user
  # 模块名
  moduleName: system
  # 包路径
  packagePath: com.rui.admin
  # 后端代码生成路径
  serveOutPath: /Users/JavaWorkSpace/my-admin/src/main/java
#  serveOutPath: D:\\Project\\my-admin\\src\\main\\java
  serveModelOutPath: /com/rui/admin
  # 前端代码生成路径
#  fontEndOutPath: /Users/JavaWorkSpace/CodeGenerator/vue-admin/src/views
  fontEndOutPath: D:\\Project\\code-generator\\vue-admin\\src\\views
  # 模板路径
#  templateRoot: /Users/JavaWorkSpace/CodeGenerator/src/main/resources/template
  template:
    controller: controller/controller.java
    mapper: mapper/mapper.java
    xml: mapper/mapper.xml
    service: service/service.java
    serviceImpl: service/impl/serviceImpl.java
    model:
      entity: model/entity/entity.java
      request: model/request/dto.java.ftl
      response: model/response/vo.java.ftl
    vue: vue/template.vue.ftl
# "" 不转义 '' 转义
