setting:
  # 作者
  author: Rui
  # 去除的表前缀,多个以 , 分隔, 不能有空格
  tablePrefix: t_,sys_
  # 表名多个以 , 分隔, 不能有空格
  tableName: t_simple,sys_employee
  # 模块名
  moduleName: simple
  # 包路径
  packagePath: com.rui
  # 后端代码生成路径
#  serveOutPath: /Users/JavaWorkSpace/CodeGenerator/src/main/java
  serveOutPath: D:\\Project\\code-generator\\src\\main\\java
  serveModelOutPath: /com/rui/admin
  # 前端代码生成路径
#  fontEndOutPath: /Users/JavaWorkSpace/CodeGenerator/vue-admin/src/views
  fontEndOutPath: D:\\Project\\code-generator\\vue-admin\\src\\views
  # 模板路径
#  templateRoot: /Users/JavaWorkSpace/CodeGenerator/src/main/resources/template
  template:
    controller: controller/controller.java
    mapper: mapper/mapper.java
    xml: mapper/mapper.xml
    service: service/service.java
    serviceImpl: service/impl/serviceImpl.java
    model:
      entity: model/entity/entity.java
      request: model/request/dto.java.ftl
      response: model/response/vo.java.ftl
    vue: vue/template.vue.ftl
# "" 不转义 '' 转义
